'use strict';

const { report } = require('../../src/version-monitor/reporter');

const UPDATES = [
	{
		source: 'npm',
		file: 'package.json',
		package: '@wordpress/scripts',
		currentValue: '^29.0.0',
		latestValue: '^30.4.1',
		is_major: true,
	},
	{
		source: 'actions',
		file: '.github/workflows/ci.yml',
		package: 'actions/setup-node',
		currentValue: 'v4.0.2',
		latestValue: 'v4.2.0',
		is_major: false,
	},
	{
		source: 'node',
		file: '.nvmrc',
		package: 'node',
		currentValue: '22.11.0',
		latestValue: '22.13.1',
		is_major: false,
	},
];

describe('report', () => {
	it('groups updates by source with a heading and a summary', () => {
		const md = report(UPDATES, { date: '2026-05-15' });
		expect(md).toContain('## Monthly version monitor - 2026-05');
		expect(md).toContain('3 updates detected across 3 source types.');
		expect(md).toContain('### npm (1)');
		expect(md).toContain('### GitHub Actions (1)');
		expect(md).toContain('### Node (1)');
		expect(md).toContain('@wordpress/scripts');
		expect(md).toContain(
			'Generated by `@rtcamp/wp-tooling/version-monitor`'
		);
	});

	it('adds a Notes column only to groups containing a major bump', () => {
		const md = report(UPDATES, { date: '2026-05-15' });
		expect(md).toContain('Major bump skipped');
		// The npm group (has a major) carries Notes; the actions group does not.
		expect(md).toContain('| Package | Current | Latest | Notes |');
		expect(md).toContain('| Action | Current | Latest |');
		expect(md).not.toContain('| Action | Current | Latest | Notes |');
	});

	it('uses singular wording for a single update', () => {
		const md = report([UPDATES[1]], { date: '2026-05-15' });
		expect(md).toContain('1 update detected across 1 source type.');
	});

	it('reports no updates cleanly', () => {
		const md = report([], { date: '2026-05-15' });
		expect(md).toContain('No updates detected.');
		expect(md).not.toContain('###');
	});
});
