/**
 * Reporter -- turns a list of update records into a markdown PR body, grouped
 * by source.
 *
 * Each source with updates gets a heading and a table; a "Notes" column
 * appears only when that group contains a major bump (which the updater skips
 * unless `--allow-major`). The output is plain markdown -- consumed as a PR
 * description, not rendered to a TTY -- so it carries no ANSI or emoji.
 *
 * Zero runtime dependencies -- Node built-ins only.
 */

'use strict';

/**
 * Source groups in report order: heading title, first-column header, and how
 * to derive that column's value from an update.
 */
const GROUPS = [
	{ source: 'npm', title: 'npm', label: 'Package', key: (u) => u.package },
	{
		source: 'actions',
		title: 'GitHub Actions',
		label: 'Action',
		key: (u) => u.package,
	},
	{ source: 'php', title: 'PHP', label: 'File', key: (u) => u.file },
	{ source: 'node', title: 'Node', label: 'File', key: (u) => u.file },
	{ source: 'wp-cli', title: 'WP-CLI', label: 'File', key: (u) => u.file },
	{
		source: 'container',
		title: 'Container images',
		label: 'Image',
		key: (u) => u.package,
	},
];

/** Note shown against a major bump that the updater will skip by default. */
const MAJOR_NOTE = 'Major bump skipped - pass `--allow-major` to apply';

/**
 * Format a `Date` (or now) as `YYYY-MM`.
 *
 * @param {Date|string} [date] Source date.
 * @return {string} Year-month string.
 */
function yearMonth(date) {
	let d = new Date();
	if (date instanceof Date) {
		d = date;
	} else if (date) {
		d = new Date(date);
	}
	return d.toISOString().slice(0, 7);
}

/**
 * Render one markdown table row.
 *
 * @param {string[]} cells Cell values.
 * @return {string} Pipe-delimited row.
 */
function row(cells) {
	return `| ${cells.join(' | ')} |`;
}

/**
 * Render the table for a single source group.
 *
 * @param {Object}   group   Group descriptor from `GROUPS`.
 * @param {Object[]} updates Updates belonging to this group.
 * @return {string[]} Markdown lines.
 */
function renderGroup(group, updates) {
	const hasMajor = updates.some((u) => u.is_major);
	const headers = [group.label, 'Current', 'Latest'];
	if (hasMajor) {
		headers.push('Notes');
	}

	const lines = [`### ${group.title} (${updates.length})`, ''];
	lines.push(row(headers));
	lines.push(row(headers.map(() => '---')));
	for (const update of updates) {
		const cells = [
			group.key(update),
			update.currentValue,
			update.latestValue,
		];
		if (hasMajor) {
			cells.push(update.is_major ? MAJOR_NOTE : '');
		}
		lines.push(row(cells));
	}
	lines.push('');
	return lines;
}

/**
 * Build the markdown PR body for a set of updates.
 *
 * @param {Object[]}    updates        Update records (annotated with `is_major`).
 * @param {Object}      [options]
 * @param {Date|string} [options.date] Report date (defaults to now).
 * @return {string} Markdown document.
 */
function report(updates = [], options = {}) {
	const month = yearMonth(options.date);
	const lines = [`## Monthly version monitor - ${month}`, ''];

	if (updates.length === 0) {
		lines.push('No updates detected.', '');
	} else {
		const present = GROUPS.filter((g) =>
			updates.some((u) => u.source === g.source)
		);
		lines.push(
			`${updates.length} update${updates.length === 1 ? '' : 's'} detected across ${present.length} source type${present.length === 1 ? '' : 's'}.`,
			''
		);
		for (const group of present) {
			const groupUpdates = updates.filter(
				(u) => u.source === group.source
			);
			lines.push(...renderGroup(group, groupUpdates));
		}
	}

	lines.push(
		'---',
		'',
		'Generated by `@rtcamp/wp-tooling/version-monitor`. Review every change before merging.'
	);
	return lines.join('\n');
}

module.exports = { report, yearMonth, GROUPS, MAJOR_NOTE };
